### ISSUE TITLE
Silently stopped syncing new messages

### ISSUE THREAD

**Issue by jefdaj** [ssbc/patchwork#839]
I haven't been able to see any new messages for about a week. No errors in the Patchwork console output. This is all it says: 

```
~/patchwork$ npm start 

> ssb-patchwork@3.10.1 start /home/jefdaj/patchwork
> electron index.js

{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  path: '/home/jefdaj/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: ...,
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [] }
Listening on http://localhost:7718/
Issues state synced 51.323s
```

What's the next step to debug it? Or is this a known issue?

**Comment by jefdaj** [comment]
Just noticed I have several posts that occur "4 months in the future".
That suggested it might be a timestamp ordering bug. I saw that mentioned somewhere as the "time travelers' bug" but can't find it now.
I fixed it temporarily by setting my system clock to 2019-01-01 and messages are rolling in again. What's the correct fix?

**Comment by mmckegg** [comment]
Hmm, interesting. 

@dominictarr do you have any ideas why setting their clock into the future would allow them to receive messages again?

**Comment by jefdaj** [comment]
I noticed another interesting detail: today I tried the same thing and didn't get any new messages, but they started again when I incremented the date to 2019-01-02. So it seems to need to increase each time. I haven't posted anything (afraid of becoming "stuck in the future") so I suppose it must not be directly related to my own feed contents. Maybe everything new last time was recorded as arriving on 2019-01-01?

**Comment by mmckegg** [comment]
@jefdaj ah! Okay, now I think I might know what is going on. 

I think you are probably still syncing, it's just that this stuff you are syncing is being stored in the log at an older time than the new stuff, so it isn't displaying in the interface. You'd probably still see a mention, or if you scrolled back far enough, you might see new stuff.

Anyway, you can fix this by deleting your database, and then waiting for it to resync.

Step by step:

- first close patchwork
- delete (or rename) the `~/.ssb/flume` directory
- reopen patchwork and wait for it to sync and index (this might take a while)
- check your profile to see if your latest messages are there!
- get back to freely reading and posting, and avoid time travel in the future ✨ 🙈

**Comment by jefdaj** [comment]
I tried deleting ~/.ssb/flume but it deletes my (visible) user info too and re-asks to set up a profile on launch. Then either way (I skip it or self-identify as "test") it sits without syncing, probably because it doesn't know about any pubs? I also tried individually deleting some of the files and folders (keys.ht, last.json, time, etc) but couldn't come up with a combination that makes it re-sync. Maybe I need to pop everything off my feed except the very first couple messages where I set my profile pic and followed a pub?

The other thing is I turned logging level up to 'info' (probably the wrong way, by editing node_modules/ssb-config/b.js) and when I set the date forward I see a lot of new messages being logged to the console, but with the date set to today nothing.

**Comment by jefdaj** [comment]
Narrowed it down to probably a bug in sbot itself rather than patchwork? If I delete ~/.ssb/{flume,db,manifest.json} (just trying to get everything) and run `node_modules/.bin/sbot server` it has the same behavior: no sync with the current date, but set to 2019-01-03 and a bunch of messages start.

I've been avoiding touching gossip.json, but maybe that has dates in it that need to be changed and/or some messages need to be removed and re-synced?

**Comment by mmckegg** [comment]
@jefdaj hmm, not sure what else to recommend apart from ditching your old identity and starting a new one at this point. I think you might be forked.

Other people that might be able to help: @dominictarr @clehner @arj03

**Comment by jefdaj** [comment]
That's OK. Thanks for the help. I was just thinking one name is a little constricting and I should adopt a cool hacker handle!

**Comment by dominictarr** [comment]
I think still a problem? sorry, I finally got to this in my github emails

**Comment by jefdaj** [comment]
Yeah it still doesn't work. I'm OK making a new identity, but at some point
another date bug might cause it to fork again. Plus I imagine it would be
hard to explain to most users why setting the date wrong can kick them off
the network in the first place.

**Comment by jefdaj** [comment]
Sorry, grad school happened for a bit and I forgot to reply! That's interesting, looks like my messages aren't being sent either then. You can't for example see this one from 2 months ago?

    %XNPVblcUY+FWQZUd9ZV3SFsfWsy+zsE7WR3+c2xvkf0=.sha256

After that I mostly stopped posting.

If I delete `~/.ssb/sbt/*` Patchwork loads but which messages I see are a little confusing. The most recent few are from 2 months in the future, then there are some from 2 months ago, and some from 10 months ago. And some of my own are missing:

    ⚠️ Missing message via jefdaj
    %IP7hmIA9oUlJFKUAbSamX8/iLTltCwVRLLYyzOrf8YI=.sha256

If I run `patchwork/node_modules/.bin/sbot server` first and then Patchwork I get `Error: no source:patchwork,channels`.

That's all with the actual date (2018-09-24). I just set it to 2019-01-05, and now it's recreating the contents of the ebt folder:

    ***............................................... (ebt:6%)

Will update when it finishes.

**Comment by jefdaj** [comment]
OK it's started receiving regular gossip again, and I think I can post too! But some messages from the time traveling times are missing, including private messages I thought I sent, but which no one replied to so maybe they just sat in my `.ssb` folder the whole without going anywhere. If they're not showing up now does that definitively mean they're not in the chain of messages other people see? Is there a way to recover them from the defunct database files? If not I'm OK letting them go.

**Comment by mmckegg** [comment]
@jefdaj if you can't see them, then I guess they were never saved

The latest version of scuttlebot (that will be included in the next patchwork release) no longer enforces message timestamp ordering, so time-travel will no longer destroy your feed. Closing!
